# Generated by Django 6.0.6 on 2026-06-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopora_app', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default=1, upload_to='products/'),
            preserve_default=False,
        ),
    ]
